# Generated by Django 3.2.8 on 2021-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodok',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
