# Generated by Django 3.2.8 on 2021-10-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.TextField(max_length=200)),
                ('nama', models.TextField(default='')),
                ('harga', models.IntegerField(default=0)),
            ],
        ),
    ]
