# Generated by Django 3.2.8 on 2021-10-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minuman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='makanan',
            new_name='minuman',
        ),
    ]
